---
title: Research Projects
---

## Neuropsychological Functioning in Pediatric Epilepsy Associated with Malformations of Cortical Development


I assisted the PI, Dr. Ana Arenivas, with moving all patient scores on the pre-determined list of cognitive assessments as well as clinical factors, into the RedCap Database in order to be analyzed in the future to determine any neuropscyhological differences in the population of interest. (This will be replaced with the abstract once made available.)

----

## Clinical and Neuropsychological Predictors of Parkinson Disease Dementia

This is an exploratory, retrospective cohort study utilizing registry and electronic health record data where we aim to assess the predictive value of the neuropsychological scores, rate of change in neuropsychological measures, cognitive phenotypes, and motor phenotypes on the diagnosis of Parkinson's disease dementia. I will be assisting the PI Dr. Darlene Floden as well as co-investigator Ekhlas Assaedi, MD in initial data analysis and creation of a potential cognitive phenotype through neuropsychological assessments.

----


## Hindbrain CB1 Receptor Agonism via CP55940 Administration Decreases Motor Behavior, But Does Not Increase Intake of Palatable Fluids


Systemic and central administration of cannabinoid CB1 receptor agonistic drugs increases intake, especially of palatable foods and fluids. Taste undoubtedly plays a role in food selection, and CB1 receptor agonism may, even in part, mediate its appetite effects via the taste system. A possible neuroanatomical site of action of these taste-guided intake effects is the hindbrain. Indeed, 4th ventricular (4icv) administration of the CB1 receptor agonist CP55940 (CP) increases intake of a palatable fluid by male and female rats in a need-free state (Miller et al 2004). We sought to replicate this and assess if the findings would extend to pure sucrose solutions.  In the present study, ad libitum-fed male (n=4) and female (n=7) Sprague-Dawley rats were anesthetized and underwent stereotaxic surgery for implantation of a 4icv cannula; analgesia and prophylactic antibiotic were provided during surgery and for 3 consecutive days following. Ten days after surgery, the rats were acclimated to sweetened condensed milk (SCM diluted in reverse osmosis water; 1:3) by providing free access to it in their home cages for 3-h sessions on each of 4 days. The rats were then, on separate days and interspersed with a 48-h washout, infused 4icv with vehicle (VEH; 0.9% sterile saline, 1μl) and CP (1ng for males, 10ng for females) immediately prior to 3-h SCM access. During both training and testing, standard chow was removed 30min prior to SCM access, and SCM intake was measured at 1h and 3h. Repeated measures 2-way ANOVA revealed no effect of CP on SCM intake; cannula functionality was confirmed by observing at least a 150% increase in blood glucose levels 45 minutes after administration of 5-thio-d-glucose (75µg, 1μl). Because our results were incongruent with previous findings, we sought to confirm that the CP was behaviorally active. Thus we assessed the motor behavior of the rats described above in an open field following VEH in one test and a higher dose of CP (30μg in 1μl, 4icv as per Miller et al 2004). in a second; infusions occurred 15min into a 30-min acclimation period that preceded the 30-min test. Videos of the tests were collected, and the duration of ambulation and number of rearing events that occurred during the 1st minute of each 5-min bin during the tests was scored under blinded conditions. Repeated measures 2-way ANOVA revealed than CP decreased ambulation and the number of times the rats reared. This confirms that the drug was behaviorally active, even though we were unable to replicate the previously reported intake effect. Overall, these findings suggest that the hindbrain is not a consistent site of action by which CB1 receptor agonists mediate their effects on appetite for palatable food.


